CREATE TABLE IF NOT EXISTS "ChatGroupMembers"(
  id SERIAL PRIMARY KEY,
  chat_group_id INT REFERENCES "ChatGroup"(id) ON DELETE CASCADE ON UPDATE CASCADE,
  chat_user_id INT REFERENCES "ChatUser"(id)  ON DELETE CASCADE ON UPDATE CASCADE
)